spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: admin
    password: Admin12345.
    url: jdbc:postgresql://localhost:5432/ecommerce-api
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  mail:
    host: smtp.gmail.com
    port: 587
    username: user@mail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true